---
- name: Install sudo
  zypper: name=sudo state=present

- name: Disable targetpw
  lineinfile:
    name: /etc/sudoers
    state: present
    regexp: '^Defaults targetpw'
    line: '#Defaults targetpw'
    validate: 'visudo -cf %s'
